from scheduler import GradualWarmupScheduler
from autoaugment import ImageNetPolicy, CIFAR10Policy, SVHNPolicy
from mixup import mixup_data, mixup_criterion
from labelsmoothing import LabelSmoothingCrossEntropy